/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.rbac.form.system;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;

import com.rbac.common.BaseForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-11-2014
 * 
 * XDoclet definition:
 * @struts.form name="accountListForm"
 */
public class AccountListForm extends BaseForm {
		
	private String usernameQry;
	
	private String realnameQry;
	
	private String query;
	
	private String del;
	
	private String deleteIds;

	public String getDel() {
		return del;
	}

	public void setDel(String del) {
		this.del = del;
	}

	public String getDeleteIds() {
		return deleteIds;
	}

	public void setDeleteIds(String deleteIds) {
		this.deleteIds = deleteIds;
	}

	public String getQuery() {
		return query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public String getRealnameQry() {
		return realnameQry;
	}

	public void setRealnameQry(String realnameQry) {
		this.realnameQry = realnameQry;
	}

	public String getUsernameQry() {
		return usernameQry;
	}

	public void setUsernameQry(String usernameQry) {
		this.usernameQry = usernameQry;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.query = null;
		this.del = null;
	}
}