/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.rbac.form.system;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;

import com.rbac.common.BaseForm;
import com.rbac.entity.SysAccount;
import com.rbac.service.AccountService;
import com.rbac.service.RoleService;
import com.rbac.util.CommonUtils;

/** 
 * MyEclipse Struts
 * Creation date: 04-21-2014
 * 
 * XDoclet definition:
 * @struts.form name="accountModifyForm"
 */
public class AccountModifyForm extends BaseForm {
	/*
	 * Generated Methods
	 */

	private String submit;
	
	private String username;
	
	private String realname;
	
	private String password;
	
	private String passwordRepeat;
	
	private String id;
	
	private String roleId;
	
	
	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPasswordRepeat() {
		return passwordRepeat;
	}

	public void setPasswordRepeat(String passwordRepeat) {
		this.passwordRepeat = passwordRepeat;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getSubmit() {
		return submit;
	}

	public void setSubmit(String submit) {
		this.submit = submit;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.submit = null;
		RoleService roleService = (RoleService)super.getBean("roleService");
		request.setAttribute("roleList", roleService.getSysRoleList(null, null));
		
		if(CommonUtils.isNotBlank(request.getParameter("id"))){
			this.setId(request.getParameter("id"));
			AccountService accountService = (AccountService) super
				.getBean("accountService");
			Long id = Long.parseLong(this.getId());
			SysAccount account = accountService.getAccountById(id);
			if(account!=null){
				this.setUsername(account.getUsername());
				this.setRealname(account.getRealname());
				
			}
		}
	}
}