/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.rbac.form.system;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;

import com.rbac.common.BaseForm;
import com.rbac.entity.SysMenu;
import com.rbac.entity.SysMenuAction;
import com.rbac.service.ActionService;
import com.rbac.service.MenuService;
import com.rbac.util.CommonUtils;

/** 
 * MyEclipse Struts
 * Creation date: 05-04-2014
 * 
 * XDoclet definition:
 * @struts.form name="menuModifyForm"
 */
public class MenuModifyForm extends BaseForm {
	
	private String submit;

	private String name;

	private String url;

	private String id;
	
	private String parentId;
	
	private String orderSeq;
	
	private String actionId;

	public String getActionId() {
		return actionId;
	}

	public void setActionId(String actionId) {
		this.actionId = actionId;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOrderSeq() {
		return orderSeq;
	}

	public void setOrderSeq(String orderSeq) {
		this.orderSeq = orderSeq;
	}

	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getSubmit() {
		return submit;
	}

	public void setSubmit(String submit) {
		this.submit = submit;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.submit = null;
		MenuService menuService = (MenuService) super
			.getBean("menuService");
		ActionService actionService = (ActionService) super
			.getBean("actionService");
		request.setAttribute("menuList", menuService.getSysMenuList(null, null));
		request.setAttribute("actionList", actionService.getSysActionList(null, null));

		// 编辑功能的反绑数据
		if (CommonUtils.isNotBlank(request.getParameter("id"))) {
			this.setId(request.getParameter("id"));
			Long id = Long.parseLong(this.getId());
			SysMenu menu = menuService.getMenuById(id);
			if (menu != null) {
				this.setName(menu.getName());
				this.setUrl(menu.getUrl());
				this.setParentId(menu.getParentId()!=null?menu.getParentId().toString():"");
				this.setOrderSeq(menu.getOrderSeq()!=null?menu.getOrderSeq().toString():"");
				List<SysMenuAction> menuActionList = menuService.getSysMenuActionByMenuId(id);
				if(menuActionList.size()>0){
					this.setActionId(menuActionList.get(0).getSysAction().getId().toString());
				}
			}
		}
	}
}