/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.rbac.form.system;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.rbac.common.BaseForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-25-2014
 * 
 * XDoclet definition:
 * @struts.form name="roleListForm"
 */
public class RoleListForm extends BaseForm {
	
	private String roleNameQry;
	
	private String roleDescQry;
	
	private String query;
	
	private String del;
	
	private String deleteIds;
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		this.query = null;
		this.del = null;
	}

	public String getDel() {
		return del;
	}

	public void setDel(String del) {
		this.del = del;
	}

	public String getDeleteIds() {
		return deleteIds;
	}

	public void setDeleteIds(String deleteIds) {
		this.deleteIds = deleteIds;
	}

	public String getQuery() {
		return query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public String getRoleDescQry() {
		return roleDescQry;
	}

	public void setRoleDescQry(String roleDescQry) {
		this.roleDescQry = roleDescQry;
	}

	public String getRoleNameQry() {
		return roleNameQry;
	}

	public void setRoleNameQry(String roleNameQry) {
		this.roleNameQry = roleNameQry;
	}
}