package com.rbac.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysAction generated by MyEclipse Persistence Tools
 */

public class SysAction implements java.io.Serializable {

	// Fields

	private Long id;

	private String name;

	private String url;

	private Short isDeleted;

	private Long creatorId;

	private Date createTime;

	private Long modifierId;

	private Date modifyTime;

	private Set sysRoleActions = new HashSet(0);

	private Set sysActionRelatesForActionId = new HashSet(0);

	private Set sysActionRelatesForRelateActionId = new HashSet(0);

	// Constructors

	/** default constructor */
	public SysAction() {
	}

	/** minimal constructor */
	public SysAction(Short isDeleted) {
		this.isDeleted = isDeleted;
	}

	/** full constructor */
	public SysAction(String name, String url, Short isDeleted, Long creatorId,
			Date createTime, Long modifierId, Date modifyTime,
			Set sysRoleActions, Set sysActionRelatesForActionId,
			Set sysActionRelatesForRelateActionId) {
		this.name = name;
		this.url = url;
		this.isDeleted = isDeleted;
		this.creatorId = creatorId;
		this.createTime = createTime;
		this.modifierId = modifierId;
		this.modifyTime = modifyTime;
		this.sysRoleActions = sysRoleActions;
		this.sysActionRelatesForActionId = sysActionRelatesForActionId;
		this.sysActionRelatesForRelateActionId = sysActionRelatesForRelateActionId;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Short getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Short isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getModifierId() {
		return this.modifierId;
	}

	public void setModifierId(Long modifierId) {
		this.modifierId = modifierId;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Set getSysRoleActions() {
		return this.sysRoleActions;
	}

	public void setSysRoleActions(Set sysRoleActions) {
		this.sysRoleActions = sysRoleActions;
	}

	public Set getSysActionRelatesForActionId() {
		return this.sysActionRelatesForActionId;
	}

	public void setSysActionRelatesForActionId(Set sysActionRelatesForActionId) {
		this.sysActionRelatesForActionId = sysActionRelatesForActionId;
	}

	public Set getSysActionRelatesForRelateActionId() {
		return this.sysActionRelatesForRelateActionId;
	}

	public void setSysActionRelatesForRelateActionId(
			Set sysActionRelatesForRelateActionId) {
		this.sysActionRelatesForRelateActionId = sysActionRelatesForRelateActionId;
	}

}