package com.rbac.entity;

import java.util.Date;

/**
 * SysAccountRole generated by MyEclipse Persistence Tools
 */

public class SysAccountRole implements java.io.Serializable {

	// Fields

	private Long id;

	private SysAccount sysAccount;

	private SysRole sysRole;

	private Integer isDeleted;

	private Long creatorId;

	private Date createTime;

	private Long modifierId;

	private Date modifyTime;

	// Constructors

	/** default constructor */
	public SysAccountRole() {
	}

	/** minimal constructor */
	public SysAccountRole(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	/** full constructor */
	public SysAccountRole(SysAccount sysAccount, SysRole sysRole,
			Integer isDeleted, Long creatorId, Date createTime,
			Long modifierId, Date modifyTime) {
		this.sysAccount = sysAccount;
		this.sysRole = sysRole;
		this.isDeleted = isDeleted;
		this.creatorId = creatorId;
		this.createTime = createTime;
		this.modifierId = modifierId;
		this.modifyTime = modifyTime;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public SysAccount getSysAccount() {
		return this.sysAccount;
	}

	public void setSysAccount(SysAccount sysAccount) {
		this.sysAccount = sysAccount;
	}

	public SysRole getSysRole() {
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole) {
		this.sysRole = sysRole;
	}

	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getModifierId() {
		return this.modifierId;
	}

	public void setModifierId(Long modifierId) {
		this.modifierId = modifierId;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}