package com.rbac.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysAccount generated by MyEclipse Persistence Tools
 */

public class SysAccount implements java.io.Serializable {

	// Fields

	private Long id;

	private String username;

	private String password;

	private String realname;

	private String salt;

	private Integer isDeleted;

	private Long creatorId;

	private Date createTime;

	private Long modifierId;

	private Date modifyTime;
	
	private String roleIds;

	private Set sysAccountRoles = new HashSet(0);

	// Constructors

	/** default constructor */
	public SysAccount() {
	}

	/** minimal constructor */
	public SysAccount(String username, String password, String salt,
			Integer isDeleted) {
		this.username = username;
		this.password = password;
		this.salt = salt;
		this.isDeleted = isDeleted;
	}

	/** full constructor */
	public SysAccount(String username, String password, String realname,
			String salt, Integer isDeleted, Long creatorId, Date createTime,
			Long modifierId, Date modifyTime, Set sysAccountRoles) {
		this.username = username;
		this.password = password;
		this.realname = realname;
		this.salt = salt;
		this.isDeleted = isDeleted;
		this.creatorId = creatorId;
		this.createTime = createTime;
		this.modifierId = modifierId;
		this.modifyTime = modifyTime;
		this.sysAccountRoles = sysAccountRoles;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getModifierId() {
		return this.modifierId;
	}

	public void setModifierId(Long modifierId) {
		this.modifierId = modifierId;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Set getSysAccountRoles() {
		return this.sysAccountRoles;
	}

	public void setSysAccountRoles(Set sysAccountRoles) {
		this.sysAccountRoles = sysAccountRoles;
	}

	public String getRoleIds() {
		return roleIds;
	}

	/**
	 * 用于保存多个roleId，多个roleId之间用半角逗号分隔
	 * @param roleIds
	 */
	public void setRoleIds(String roleIds) {
		this.roleIds = roleIds;
	}

}