package com.rbac.entity;

import java.util.Date;

/**
 * SysActionRelate generated by MyEclipse Persistence Tools
 */

public class SysActionRelate implements java.io.Serializable {

	// Fields

	private Long id;

	private SysAction sysActionByActionId;

	private SysAction sysActionByRelateActionId;

	private Short isDeleted;

	private Long creatorId;

	private Date createTime;

	private Long modifierId;

	private Date modifyTime;

	// Constructors

	/** default constructor */
	public SysActionRelate() {
	}

	/** minimal constructor */
	public SysActionRelate(Short isDeleted) {
		this.isDeleted = isDeleted;
	}

	/** full constructor */
	public SysActionRelate(SysAction sysActionByActionId,
			SysAction sysActionByRelateActionId, Short isDeleted,
			Long creatorId, Date createTime, Long modifierId, Date modifyTime) {
		this.sysActionByActionId = sysActionByActionId;
		this.sysActionByRelateActionId = sysActionByRelateActionId;
		this.isDeleted = isDeleted;
		this.creatorId = creatorId;
		this.createTime = createTime;
		this.modifierId = modifierId;
		this.modifyTime = modifyTime;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public SysAction getSysActionByActionId() {
		return this.sysActionByActionId;
	}

	public void setSysActionByActionId(SysAction sysActionByActionId) {
		this.sysActionByActionId = sysActionByActionId;
	}

	public SysAction getSysActionByRelateActionId() {
		return this.sysActionByRelateActionId;
	}

	public void setSysActionByRelateActionId(SysAction sysActionByRelateActionId) {
		this.sysActionByRelateActionId = sysActionByRelateActionId;
	}

	public Short getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Short isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getModifierId() {
		return this.modifierId;
	}

	public void setModifierId(Long modifierId) {
		this.modifierId = modifierId;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}