package com.rbac.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysMenu generated by MyEclipse Persistence Tools
 */

public class SysMenu implements java.io.Serializable {

	// Fields

	private Long id;

	private SysMenu sysMenu;

	private String name;

	private String url;

	private Integer needCheck;

	private Integer isShow;

	private Integer isDeleted;

	private Long creatorId;

	private Date createTime;

	private Long modifierId;

	private Date modifyTime;

	private Set sysMenus = new HashSet(0);

	private Set sysRoleMenus = new HashSet(0);

	private Set sysMenuActions = new HashSet(0);

	// Constructors

	/** default constructor */
	public SysMenu() {
	}

	/** minimal constructor */
	public SysMenu(Integer needCheck, Integer isShow, Integer isDeleted) {
		this.needCheck = needCheck;
		this.isShow = isShow;
		this.isDeleted = isDeleted;
	}

	/** full constructor */
	public SysMenu(SysMenu sysMenu, String name, String url, Integer needCheck,
			Integer isShow, Integer isDeleted, Long creatorId, Date createTime,
			Long modifierId, Date modifyTime, Set sysMenus, Set sysRoleMenus,
			Set sysMenuActions) {
		this.sysMenu = sysMenu;
		this.name = name;
		this.url = url;
		this.needCheck = needCheck;
		this.isShow = isShow;
		this.isDeleted = isDeleted;
		this.creatorId = creatorId;
		this.createTime = createTime;
		this.modifierId = modifierId;
		this.modifyTime = modifyTime;
		this.sysMenus = sysMenus;
		this.sysRoleMenus = sysRoleMenus;
		this.sysMenuActions = sysMenuActions;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public SysMenu getSysMenu() {
		return this.sysMenu;
	}

	public void setSysMenu(SysMenu sysMenu) {
		this.sysMenu = sysMenu;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getNeedCheck() {
		return this.needCheck;
	}

	public void setNeedCheck(Integer needCheck) {
		this.needCheck = needCheck;
	}

	public Integer getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Integer isShow) {
		this.isShow = isShow;
	}

	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getModifierId() {
		return this.modifierId;
	}

	public void setModifierId(Long modifierId) {
		this.modifierId = modifierId;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Set getSysMenus() {
		return this.sysMenus;
	}

	public void setSysMenus(Set sysMenus) {
		this.sysMenus = sysMenus;
	}

	public Set getSysRoleMenus() {
		return this.sysRoleMenus;
	}

	public void setSysRoleMenus(Set sysRoleMenus) {
		this.sysRoleMenus = sysRoleMenus;
	}

	public Set getSysMenuActions() {
		return this.sysMenuActions;
	}

	public void setSysMenuActions(Set sysMenuActions) {
		this.sysMenuActions = sysMenuActions;
	}

}