/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.rbac.action.system;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.rbac.form.system.AccountModifyForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-21-2014
 * 
 * XDoclet definition:
 * @struts.action path="/accountModify" name="accountModifyForm" input="/system/accountModify.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/system/accountList.jsp"
 */
public class AccountModifyAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AccountModifyForm accountModifyForm = (AccountModifyForm) form;
		return mapping.getInputForward();
	}
}