/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.rbac.action.system;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.rbac.common.BaseAction;
import com.rbac.form.system.ActionListForm;
import com.rbac.service.ActionService;
import com.rbac.util.CommonUtils;

/** 
 * MyEclipse Struts
 * Creation date: 04-30-2014
 * 
 * XDoclet definition:
 * @struts.action path="/actionList" name="actionListForm" input="/system/actionList.jsp" scope="request" validate="true"
 */
public class ActionListAction extends BaseAction {
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ActionListForm actionListForm = (ActionListForm) form;
		ActionService actionService = (ActionService) super
				.getBean("actionService");
		if (CommonUtils.isNotBlank(actionListForm.getDel())) {
			actionService.deleteAction(Long.parseLong(actionListForm
					.getDeleteIds()), super.getCurrentAccountId(request));
		}
		List actionList = actionService.getSysActionList(actionListForm
				.getNameQry(), actionListForm.getUrlQry());
		request.setAttribute("actionList", actionList);
		return mapping.getInputForward();
	}
}