/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.rbac.action.system;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import java.util.Map;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.commons.beanutils.PropertyUtils;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Hibernate;
import org.hibernate.collection.PersistentBag;

import com.rbac.common.BaseAction;
import com.rbac.common.MvcConstant;
import com.rbac.entity.SysAccount;
import com.rbac.entity.SysAccountRole;
import com.rbac.entity.SysRole;
import com.rbac.form.system.LoginForm;
import com.rbac.service.AccountService;
import com.rbac.service.LoginService;

/**
 * MyEclipse Struts Creation date: 12-20-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/login" name="LoginForm" input="/login.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="success" path="/index.jsp"
 */
public class LoginAction extends BaseAction {

	
	private static final Log logger = LogFactory.getLog(LoginAction.class);
	
	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;
		LoginService loginService = (LoginService) super
				.getBean("loginService");
		if (StringUtils.isNotBlank(loginForm.getPassword())) {
			SysAccount account = loginService.login(loginForm.getUsername(),
					loginForm.getPassword());
			if (account != null) {
				request.getSession(true).setAttribute(MvcConstant.USER, account);
				return mapping.findForward("success");
			}
		}
		request.setAttribute("errormsg", "用户名或密码不正确");
		loginForm.setPassword("");
					
		return mapping.getInputForward();
	}
	
	
}