/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.rbac.action.system;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.rbac.common.BaseAction;
import com.rbac.form.system.MenuListForm;
import com.rbac.service.MenuService;
import com.rbac.util.CommonUtils;

/** 
 * MyEclipse Struts
 * Creation date: 05-04-2014
 * 
 * XDoclet definition:
 * @struts.action path="/menuList" name="menuListForm" input="/system/menuList.jsp" scope="request" validate="true"
 */
public class MenuListAction extends BaseAction {

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		MenuListForm menuListForm = (MenuListForm) form;
		MenuService menuService = (MenuService) super
				.getBean("menuService");
		if (CommonUtils.isNotBlank(menuListForm.getDel())) {
			menuService.deleteMenu(Long.parseLong(menuListForm
					.getDeleteIds()), super.getCurrentAccountId(request));
		}
		List menuList = menuService.getSysMenuList(menuListForm
				.getNameQry(), menuListForm.getUrlQry());
		request.setAttribute("menuList", menuList);
		return mapping.getInputForward();
	}
}