/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.rbac.action.system;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.rbac.common.BaseAction;
import com.rbac.form.system.RoleListForm;
import com.rbac.service.RoleService;
import com.rbac.util.CommonUtils;

/**
 * MyEclipse Struts Creation date: 04-25-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/roleList" name="roleListForm"
 *                input="/system/roleList.jsp" scope="request" validate="true"
 */
public class RoleListAction extends BaseAction {

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RoleListForm roleListForm = (RoleListForm) form;
		RoleService roleService = (RoleService) super
				.getBean("roleService");
		if (CommonUtils.isNotBlank(roleListForm.getDel())) {
			roleService.deleteRole(Long.parseLong(roleListForm
					.getDeleteIds()), super.getCurrentAccountId(request));
		}
		List roleList = roleService.getSysRoleList(roleListForm
				.getRoleNameQry(), roleListForm.getRoleDescQry());
		request.setAttribute("roleList", roleList);
		return mapping.getInputForward();
	}
}