/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.rbac.form.user;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;

import com.rbac.common.BaseForm;
import com.rbac.entity.SysAccount;
import com.rbac.service.AccountService;

/** 
 * MyEclipse Struts
 * Creation date: 04-30-2014
 * 
 * XDoclet definition:
 * @struts.form name="pwdModifyForm"
 */
public class PwdModifyForm extends BaseForm {

	private String submit;
	
	private String password;
	
	private String passwordRepeat;
	
	private String id;

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		Long accountId = this.getCurrentAccountId(request);
		this.setId(accountId.toString());
		AccountService accountService = (AccountService) super
				.getBean("accountService");
		SysAccount account = accountService.getAccountById(accountId);;
		request.setAttribute("account",account);
	}

	public String getId() {
		return id;
	}

	public void setId(String accountId) {
		this.id = accountId;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPasswordRepeat() {
		return passwordRepeat;
	}

	public void setPasswordRepeat(String passwordRepeat) {
		this.passwordRepeat = passwordRepeat;
	}

	public String getSubmit() {
		return submit;
	}

	public void setSubmit(String submit) {
		this.submit = submit;
	}
}